package oopsPractical;

/*Uses of Constructor
 * --Use to write buss logiv that will be executed at the time of obj creation
 * --Use to initilize instance variable
 * */
public class Constrdemo 
{
	int stud_age;
	String stud_sub;
	int marks;
	
    Constrdemo()
    {
       /* rule for declare constructor
        --> class name for and constructor name should be same
    	--> constructor can not have return type
    	--> constructor able to take parameter */
    	System.out.println("Default constructor");	
    }
    
    Constrdemo(int id,String name)
    {
      System.out.println("ID is "+id);
      System.out.println("Name is "+name);
    }
    //constructor generated by default
	public void display()
	{
		System.out.println("Demo practical");
	}
	Constrdemo(int age,String sub,int marks)//local variable
	{
	// scope of local variable is limited to this constructor only
	//so we have to do conversion 
		stud_age=age;
		stud_sub=sub;
		this.marks=marks;// this point to instance var when local variable name and
		                 //instance variable name is same then we use this keyword
		                 //to represent instance variable
	}
	public void show()
	{
		//System.out.println("Student age is"+age); 
		//This is give error because age is local variable and its scope is limited to the constructor only
		
		System.out.println("Student age is "+stud_age);
		System.out.println("Student subject is "+stud_sub);
		System.out.println("Student marks is "+marks);
	}
	
	public static void main(String[] args) 
	{
		Constrdemo c=new Constrdemo();
		c.display();
		//Constrdemo-- is class name
		// c --ref to object
		// new -- keyword to create object
		//Constrdemo()-- is constructor 
		
		Constrdemo c1=new Constrdemo(10,"Neha");
		Constrdemo c2=new Constrdemo(24,"Mathematics",80);
		c2.show();
	}

}




